#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
BİST Fırsat Taraması - Dip Dönüş Algoritması
Aşırı satılmış, hacimli dönüş yapan hisseleri bulur.
"""

import yfinance as yf
import pandas as pd
import numpy as np
from datetime import datetime
import requests
import time

# TELEGRAM BİLGİLERİ
TELEGRAM_TOKEN = "8455173046:AAECKdZcTVnt3naPDzI3udwwfj23nyv4uMs"
TELEGRAM_CHAT_ID = "-1003670397485"

# BİST HİSSE LİSTESİ (TAMAMI)
BIST_HISSELER = """
QNBTR,ASELS,KLRHO,GARAN,ENKAI,KCHOL,THYAO,AKBNK,FROTO,TUPRS,BIMAS,VAKBN,HALKB,YKBNK,DSTKF,TCELL,TTKOM,SAHOL,CCOLA,EREGL,KENT,ASTOR,GUBRF,TOASO,TRALT,HEDEF,TERA,SISE,MAGEN,OYAKC,ISDMR,ENJSA,TAVHL,AEFES,TURSG,MGROS,SASA,QNBFK,PGSUS,ZRGYO,BRSAN,KLNMA,DMLKT,MPARK,PASEU,ARCLK,AKSEN,AGHOL,ECILC,TRGYO,KTLEV,ENERY,ISMEN,TABGD,UFUK,BRYAT,CVKMD,AHGAZ,LYDHO,LIDER,GLRMK,PEKGY,RYGYO,RALYH,TBORG,SELEC,OTKAR,DOHOL,TTRAK,ANSGR,TRMET,RGYAS,AYGAZ,ANHYT,ULKER,CIMSA,EFOR,ALARK,PETKM,BSOKE,DOAS,CLEBI,AGESA,ODINE,INVES,AKSA,SOKM,TSKB,AKCNS,MAVI,IEYHO,GRSEL,SARKY,RYSAS,YGGYO,RAYSG,NUHCM,GENIL,ECZYT,CWENE,DAPGM,ADGYO,PAHOL,KRDMA,GRTHO,BASGZ,CMENT,GLYHO,TKFEN,BTCIM,BRISA,HEKTS,TEHOL,TRENJ,EUPWR,KLYPV,ALKLC,SKBNK,BMSTL,LYDYE,GESAN,CEMZY,NTHOL,KUYAS,OBAMS,ALBRK,POLTK,IZENR,AKFYE,OZKGY,EGEEN,KCAER,ARMGD,KONYA,AVPGY,MOGAN,ENTRA,TRHOL,AKSGY,ISGYO,ARASE,MIATK,BFREN,BINBN,SNGYO,FENER,KLKIM,LILAK,BALSU,SUNTK,ISKPL,CANTE,BANVT,AYDEM,VERUS,ZOREN,PSGYO,HLGYO,MEGMT,CRFSA,MRSHL,KZBGY,OYYAT,ASUZU,AHSGY,GSRAY,ENSRI,LMKDC,AKFIS,ALFAS,MOPAS,ALTNY,ULUSE,FZLGY,DEVA,KLSER,SMRTG,YYLGD,LOGO,YEOTK,ARDYZ,EGPRO,KSTUR,GWIND,KAYSE,TCKRC,ISFIN,KONTR,KOTON,JANTS,TRCAS,HTTBT,VESBE,PATEK,TMSN,ECOGR,DOFRB,AKGRT,POLHO,AYCES,ESCAR,BINHO,TUKAS,VAKFA,ICBCT,BULGS,BERA,NETCD,IZMDC,BARMA,OZATD,MEYSU,PRKAB,SONME,SDTTR,EUREN,ZERGY,KBORU,AKFGY,GARFA,TATEN,ALGYO,SRVGY,MOBTL,A1CAP,TNZTP,KORDS,VAKKO,VESTL,DGGYO,OFSYM,VSNMD,GOZDE,VAKFN,VKGYO,BUCIM,GLCVY,GUNDG,BASCM,GEREL,BESLR,BIGTK,INGRM,EBEBK,ADEL,KLGYO,ALCAR,GEDIK,EGGUB,ALKA,BIENY,HRKET,SURGY,INVEO,KARSN,BIOEN,SNPAM,IZFAS,BOSSA,HATSN,QUAGR,KAPLM,PARSN,ODAS,TUREX,TARKM,SEGMN,KOPOL,MAALT,ATAKP,DOKTA,PAGYO,GIPTA,TSPOR,BOBET,AKMGY,AKENR,NTGAZ,AYEN,ASGYO,ARSAN,AGROT,IHAAS,BLUME,KAREL,KMPUR,GMTAS,YIGIT,GOKNR,INTEM,BAHKM,AKHAN,ONCSM,SMRVA,GENTS,ESEN,ISGSY,DITAS,CRDFA,KGYO,MNDTR,BJKAS,ENDAE,TEZOL,NATEN,CATES,GOLTS,YATAS,KRVGD,REEDR,EGEGY,UCAYM,EKOS,KOCMT,KATMR,INDES,DMRGD,CGCAM,CEMTS,ALVES,KONKA,BORSK,FORTE,KARTN,BRKVY,MERIT,TMPOL,YBTAS,ADESE,BIGEN,DESA,ALKIM,PLTUR,AFYON,HOROZ,PENTA,EGEPO,ORGE,ULUUN,DARDL,BURVA,OZYSR,SAFKR,ARFYE,BURCE,ALCTL,TSGYO,LINK,KZGYO,CEMAS,SOKE,SUWEN,GSDHO,TKNSA,SEGYO,BIGCH,ERCB,YUNSA,AZTEK,FMIZP,MHRGY,YAPRK,ONRYT,ORMA,USAK,BVSAN,DYOBY,PKENT,KUTPO,DUNYH,ANELE,KIMMR,GOODY,MNDRS,IMASM,INFO,ELITE,EDATA,NETAS,GATEG,ERBOS,MEKAG,DZGYO,BAGFS,TURGG,GZNMI,BEGYO,PETUN,ATATP,MANAS,PNSUT,PAPIL,HDFGS,AYES,KLSYN,LKMNH,TATGD,MERCN,FORMT,BLCYT,NUGYO,KTSKR,EKSUN,MEDTR,SERNT,RUZYE,CMBTN,SAYAS,BRLSM,KUVVA,HUNER,OSMEN,MAKTK,SANKO,LIDFA,KNFRT,CELHA,IHLAS,ISSEN,HURGZ,DCTTR,EMKEL,PINSU,PNLSN,TRILC,BYDNR,FONET,YYAPI,KRGYO,BEYAZ,LRSHO,MARBL,PRKME,METRO,UNLU,LUKSK,TEKTU,MACKO,SKYLP,MRGYO,BAKAB,CONSE,DURKN,DNISI,MSGYO,FRIGO,PAMEL,ARENA,RUBNS,ARTMS,ESCOM,KRONT,DERHL,VBTYZ,ATEKS,SNICA,GLRYH,PCILT,SANFM,BIZIM,OTTO,DAGI,SELVA,ANGEN,KLMSN,EDIP,OZSUB,TGSAS,EGSER,KRSTL,EYGYO,MTRKS,ULUFA,OZGYO,VERTU,ISBIR,VRGYO,DERIM,TLMAN,INTEK,KFEIN,DGATE,AGYO,IHLGM,EUHOL,RTALB,CUSAN,SKTAS,OSTIM,BRKO,DURDO,BORLS,MERKO,SKYMD,MAKIM,TDGYO,MEPET,TUCLK,ARZUM,OBASE,DMSAS,DENGE,DGNMO,DOFER,VANGD,MARTI,BMSCH,A1YEN,PKART,AVGYO,YKSLN,BNTAS,KRPLS,SUMAS,COSMO,NIBAS,DOGUB,PENGD,GLBMD,ZEDUR,OZRDN,GSDDE,ISYAT,BALAT,AVHOL,AKSUE,MMCAS,PRDGS,RNPOL,GEDZA,SODSN,YAYLA,FADE,HKTM,AVOD,VKING,EPLAS,YESIL,BAYRK,IHGZT,VKFYO,KERVN,EKIZ,ACSEL,IZINV,DESPC,HUBVC,OYAYO,SEYKM,FLAP,ICUGS,EMNIS,CEOEM,SMART,ETILR,SILVR,YONGA,HATEK,SEKFK,PSDTC,KRTEK,SEKUR,ORCAY,IHYAY,BRMEN,PRZMA,BRKSN,MEGAP,IHEVA,AVTUR,ULAS,MARKA,SANEL,MZHLD,AKYHO,OYLUM,SAMAT,IDGYO,GRNYO,ATAGY,ERSU,RODRG,ATLAS,ETYAT,CASA,ATSYH,MTRYO,EUKYO,EUYO,DIRIT,FRMPL,BESTE,ALTIN,ZGYO,MARMR
""".replace('\n', '').strip()

HISSE_LISTESI = [h.strip() + '.IS' for h in BIST_HISSELER.split(',') if h.strip()]

def telegram_gonder(mesaj):
    try:
        url = f"https://api.telegram.org/bot{TELEGRAM_TOKEN}/sendMessage"
        data = {"chat_id": TELEGRAM_CHAT_ID, "text": mesaj, "parse_mode": "HTML"}
        requests.post(url, data=data, timeout=10)
    except: pass

def calculate_rsi(prices, period=14):
    delta = prices.diff()
    gain = (delta.where(delta > 0, 0)).rolling(window=period).mean()
    loss = (-delta.where(delta < 0, 0)).rolling(window=period).mean()
    rs = gain / loss
    return 100 - (100 / (1 + rs))

def hisse_analiz(ticker):
    try:
        stock = yf.Ticker(ticker)
        df = stock.history(period="6mo")
        if df.empty or len(df) < 50: return None
        
        # Teknik Göstergeler
        df['RSI'] = calculate_rsi(df['Close'])
        df['EMA5'] = df['Close'].ewm(span=5).mean()
        df['EMA21'] = df['Close'].ewm(span=21).mean()
        avg_vol = df['Volume'].rolling(20).mean()
        
        last = df.iloc[-1]
        prev = df.iloc[-2]
        
        # --- ÖZEL FIRSAT FİLTRESİ (DİP DÖNÜŞ) ---
        firsat_mi = (
            last['RSI'] > 30 and last['RSI'] < 52 and       # RSI dipten yeni dönüyor
            last['Volume'] > (avg_vol.iloc[-1] * 1.8) and # Hacim patlaması (1.8 kat)
            last['Close'] > last['EMA5'] and              # Fiyat EMA5 üstüne atmış
            last['EMA5'] > prev['EMA5']                   # EMA5 yönünü yukarı kırmış
        )
        
        if not firsat_mi: return None
        
        return {
            'ticker': ticker.replace('.IS', ''),
            'fiyat': last['Close'],
            'rsi': last['RSI'],
            'hacim_artis': last['Volume'] / avg_vol.iloc[-1]
        }
    except: return None

def main():
    telegram_gonder("🎯 <b>BİST Dip Dönüş Fırsat Taraması Başladı...</b>")
    bulunanlar = []
    for ticker in HISSE_LISTESI:
        res = hisse_analiz(ticker)
        if res: bulunanlar.append(res)
        time.sleep(0.2)
    
    if not bulunanlar:
        telegram_gonder("⚠️ Bugün kriterlere uygun dip dönüş fırsatı bulunamadı.")
    else:
        msg = "🔥 <b>POTANSİYEL DİP DÖNÜŞ FIRSATLARI</b>\n\n"
        for h in bulunanlar:
            msg += f"✅ <b>#{h['ticker']}</b>\n💰 Fiyat: {h['fiyat']:.2f} TL\n📊 RSI: {h['rsi']:.1f}\n📈 Hacim: {h['hacim_artis']:.1f}x Katı\n\n"
        telegram_gonder(msg)

if __name__ == "__main__":
    main()
